---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
              echo "Hello World!"
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
              echo "Hello World!"


workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-deploy-workflow:
    jobs:
    - build
    